name: CI
on:
  pull_request:
    branches: [ master, main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: [self-hosted, nixos, hetzner]
    steps:
      - uses: actions/checkout@v4

      - name: Clone nostrdb with submodules
        run: |
          git clone https://github.com/damus-io/nostrdb.git --depth 1
          cd nostrdb
          git submodule update --init --recursive --depth 1
          cd ..

      - name: Run CI tests with Nix
        run: |
          nix run .#ci --impure --option sandbox false

      # Build is disabled due to C header path issues in Nix environment
      # This is a known Zig + Nix issue when compiling C dependencies
      # See: https://github.com/NixOS/nixpkgs/issues/86506
      #- name: Build project with Nix
      #  run: |
      #    nix build --impure --option sandbox false

      #- name: Verify megalith CLI exists
      #  run: |
      #    # Check that the megalith binary was built
      #    if [ -f ./result/bin/megalith ]; then
      #      echo "✓ Megalith CLI binary found"
      #      ./result/bin/megalith --help || echo "Note: megalith may not have --help flag"
      #    else
      #      echo "Warning: Megalith CLI not found in result/bin/"
      #      ls -la ./result/ || echo "No result directory"
      #    fi

      - name: Auto-merge PR
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Auto-merging PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --squash \
            --delete-branch \
            --auto