name: CI
on:
  pull_request:
    branches: [ master, main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive --depth 1

      - name: Run CI tests with Nix
        run: |
          nix run .#ci --impure --option sandbox false

      - name: Build SSR demo package (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          nix build .#ssr-demo --impure --option sandbox false

      - name: Build SSR demo with Zig (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          nix develop -c bash -lc "zig build ssr-demo -Doptimize=Debug"

      - name: Auto-merge PR
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Auto-merging PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --squash \
            --delete-branch \
            --auto
